name: Create PR from contributor to master

on:
  push:
    branches:
      - contributor # trigger on any push to contributor

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: contributor # head of the PR
          destination_branch: master # base of the PR
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Daily content sync"
          pr_body: |
            Automatic PR: sync changes from contributor to master.
          pr_draft: false
