# .github/workflows/create-content-pr.yml
name: Create PR from contributor to master

on:
  push:
    branches:
      - contributor

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout contributor branch
        uses: actions/checkout@v4
        with:
          ref: contributor

      - name: Create or update PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(content): update from TinaCMS"
          branch: contributor
          base: master
          title: "Daily content sync"
          body: |
            TinaCMS content edits made in `contributor`. This PR syncs them to `master`.
          draft: false
          delete-branch: false
          # Prevent duplicate PRs
          create-branch: false
