# .github/workflows/merge-content-pr.yml
name: Auto Merge Content PR

on:
  schedule:
    - cron: "30 * * * *" # 8:00 AM IST
  workflow_dispatch:

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find open PR from contributor to master
        id: find_pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
              base: "master",
              head: `${context.repo.owner}:contributor`,
            });

            if (prs.data.length > 0) {
              const pr = prs.data[0];
              console.log(`Found PR: #${pr.number}`);
              return pr.number;
            }

            return null;

      - name: Merge the PR
        if: steps.find_pr.outputs.result != 'null'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = Number(${{ steps.find_pr.outputs.result }});
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: "squash"
            });
            console.log(`Merged PR #${prNumber}`);
